@startuml
title Process Releationship
:patient: -> (Consents) : patient specific rules

:user: -> (UserApp) : access data 
(UserApp) -> (AccessControl): Is any access allowed?
Note right of (AccessControl): Org policies & Consents
(AccessControl) --> (Consents): Get patient specific rules
(UserApp) <-- (AccessControl): Yes, but only non sensitive

(UserApp) -> (EHR) : Request data given\nAccessControl token
(SLS) <-- (EHR) : request to tag search results
(AccessEnforcement) <-- (SLS): tagged data
(UserApp) <-- (AccessEnforcement): allowed data

@enduml
