# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: johnmoehrke.consentwithsegmentation
canonical: http://johnmoehrke.github.io/ConsentWithSegmentation
name: JohnMoehrke_ConsentWithSegmentation
title: "JohnMoehrke Consent with Segmented data"
description: "This Implementation Guide addresses privacy Consent resource with segmented data."
status: draft
version: 0.1.0-current
fhirVersion: 4.3.0
#fhirVersion: 4.3.0-snapshot1
#fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: ci-build
publisher:
  name: John Moehrke (himself)
  url: http://healthcaresecprivacy.blogspot.com
  email: JohnMoehrke@gmail.com
contact:
  - name: John Moehrke (himself)
    telecom:
      - system: email
        value: JohnMoehrke@gmail.com
license: CC-BY-4.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
extension: 
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: draft
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 0
dependencies:
  us.nlm.vsac: 0.8.0

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - fsh-generated/resources
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  fmm-definition: maturity.html
  propagate-status: 'true'

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Consents: consent.html
  SLS: sls.html
  Maturity: maturity.html
  Informative: informative.html
  Artifacts: artifacts.html

# marking pages as informative, causes all unmarked to be marked informative. So if you mark one page, then you need to mark them all. https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/structuredefinition-standards-status
pages:
  index.md:
    title: specification
    generation: markdown
  consent.md:
    title: Consent Profiling
    generation: markdown
  sls.md:
    title: Security Labeling Service
    generation: markdown
  maturity.md:
    title: Redefined FMM
    generation: markdown
  informative.md:
    title: Informative stuff
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative




    